export const PAYMENT_PROCESS_REQUESTED = "PAYMENT_PROCESS_REQUESTED";
export const PAYMENT_RETRY_REQUESTED = "PAYMENT_RETRY_REQUESTED";
export const WEBHOOK_DELIVERIES_REQUESTED = "WEBHOOK_DELIVERIES_REQUESTED";
export const WEBHOOK_DELIVERY_REQUESTED = "WEBHOOK_DELIVERY_REQUESTED";
